### ISSUE TITLE
site clocks in at a gigantic 2.1 mb downloaded in chrome on first load

### ISSUE THREAD

**Issue by wchristian** [dnmfarrell/perldotcom#39]
Looks like a whole bunch of full-size images for "behind the fold" stuff are automatically downloaded on first load.

**Comment by dnmfarrell** [comment]
I agree that it could be better. I think the majority of the download size is caused by article thumbnails being resized instead of using lower quality smaller images as thumbnails. We do have a `thumbnail` front matter property that can be used to provide the thumbnail image.

So to fix this, we simply need to update all 30 of the latest articles with a thumbnail. That sounds scriptable, so we might as well update all articles under `content/article` that are missing a thumbnail.

**Comment by dnmfarrell** [comment]
All articles with images have been given thumbnails: these are typically 1/3 of the size of the articles' cover image. Testing the site now, I see 1.5MB of content downloaded, so we've saved about 1MB.

I disagree that 2.5mb is "gigantic" though, compared to other tech sites:

* ArsTechnica.com - 4.7MB
* SlashDot.org - 3.1MB
* www.theregister.co.uk - 1.5MB
* drdobbs.com - 2.3 MB

We could reduce the size further by restricting the number of articles listed on the homepage. If we cut it to 15 from 30, that could save approximately another 2/3 MB. Let me think about that.

**Comment by dnmfarrell** [comment]
@wchristian the home page now clocks in at a svelte 1.1MB

**Comment by wchristian** [comment]
Definitely makes a difference on my phone. :)
