### ISSUE TITLE
a lot of basic navigation links are missing alt-fields

### ISSUE THREAD

**Issue by wchristian** [dnmfarrell/perldotcom#48]
Particularly the "more" icons top right are bad about that.

**Comment by dnmfarrell** [comment]
A quick glance shows almost every link missing this

**Comment by j-afarian** [comment]
From an accessibility standpoint, basic text links should not include alt attributes. Alt is meant to be alternative text for an `<img>`, `<area>`, or `<input>`.

The main navigation links (About, Authors, Categories, Tags) have empty alt attributes on their images and are hidden from screen readers. This is recommended practice since their images are purely decorative and do not convey meaning.

Aside from the Github icon (which currently has an alt attribute of "GH", and does not convey its purpose clearly), I'm unsure what exactly needs changing here.

**Comment by wchristian** [comment]
Maybe things were changed in the meantime, looks ok now.

**Comment by dnmfarrell** [comment]
Thanks for clarifying the issue @j-afarian.
I can't remember if I updated the alt tags since this was originally opened, I might have. I've fixed the GitHub logo img alt attribute.
Given @wchristian positive feedback, am closing this issue.
