### ISSUE TITLE
Get Sawyer's author info

### ISSUE THREAD

**Issue by briandfoy** [dnmfarrell/perldotcom#51]
Get Sawyer's author info. I've already emailed him asking for a pull request.

- [ ] Picture _static/images/author/sawyerx.jpg_
- [ ] JSON data _data/author/sawyerx.json_

**Comment by dnmfarrell** [comment]
Hey I want to make it as easy as possible for new authors to contribute an article: to the extent that I will write the author bio entry on their behalf, and then ask for their approval of it, rather than asking them to send a PR.
It's a simpler process for new authors to ask them "just send us an article - via PR or email" and once we have a draft article, write their bio, ask them for a thumbs up, and take it from there.
